# Jekyll configuration for GitHub Pages redirects
plugins:
  - jekyll-redirect-from

# Global redirect for GitHub Pages to main domain
url: "https://docs.fused.io"

# Redirect all GitHub Pages traffic to main domain
redirect_to: https://docs.fused.io
