import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "category",
      label: "Basics",
      link: { type: "doc", id: "basics/index" },
      items: [
        "basics/quickstart/quickstart",
        "basics/core-concepts",
        {
          type: "category",
          label: "Get data in",
          link: { type: "doc", id: "basics/in" },
          items: [{ type: "autogenerated", dirName: "basics/in" }],
        },
        {
          type: "category",
          label: "Transform data",
          collapsed: false,
          link: { type: "doc", id: "basics/transform" },
          items: [
            {
              type: "category",
              label: "Join operations",
              collapsed:false, 
              items: [
                { type: "autogenerated", dirName: "basics/transform/join" }
              ],
            },
            {
              type: "category",
              label: "Raster operations",
              collapsed:true,
              items: [
                { type: "autogenerated", dirName: "basics/transform/raster" }
              ],
            },
            {
              type: "category",
              label: "Vector operations",
              collapsed:true,
              items: [
                { type: "autogenerated", dirName: "basics/transform/vector" }
              ],
            },
            {
              type: "category",
              label: "H3 operations",
              collapsed:true,
              items: [
                { type: "autogenerated", dirName: "basics/transform/h3" }
              ],
            },
            {
              type: "category",
              label: "Advanced operations",
              collapsed:true,
              items: [
                { type: "autogenerated", dirName: "basics/transform/advanced" }
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Get data out",
          link: { type: "doc", id: "basics/out" },
          items: [{ type: "autogenerated", dirName: "basics/out" }],
        },
        {
          type: "category",
          label: "Tutorials",
          link: { type: "doc", id: "basics/tutorials" },
          items: [{ type: "autogenerated", dirName: "basics/tutorials" }],
        },
        {
          type: "category",
          label: "Use cases",
          // link: { type: "doc", id: "basics/usecases" },
          items: [{ type: "autogenerated", dirName: "basics/usecases" }],
        },
        "basics/utilities",
        "basics/faq",
      ],
    },
    {
      type: "category",
      label: "Python SDK",
      link: { type: "doc", id: "python-sdk/index" },
      items: ["python-sdk/top-level-functions", require("./docs/reference/sidebar.json"), "python-sdk/dependencies", "python-sdk/changelog"],
    },
    {
      type: "category",
      label: "Workbench",
      link: { type: "doc", id: "workbench/index" },
      items: [
        "workbench/udf-editor",
        "workbench/navigation",
        "workbench/map",
        "workbench/results",
        "workbench/viz-styling",
      ],
    },
    "contribute"
  ],
};

export default sidebars;
