name: Crawl

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  algolia-docs-indexing:
    runs-on: ubuntu-latest
    steps:
      - name: Algolia Crawler Automatic Crawl
        uses: algolia/algoliasearch-crawler-github-actions@v1.1.13
        with:
          crawler-user-id: ${{ secrets.ALGOLIA_CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.ALGOLIA_CRAWLER_API_KEY }}
          github-token: ${{ github.token }}
          crawler-name: "fused"
          algolia-app-id: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: "https://docs.fused.io"
