name: Delete PR prefix on merge
run-name: Delete PR prefix on merge

on:
    pull_request:
        types: [closed]

permissions:
    id-token: write
    contents: read

env:
    BUCKET_NAME: 's3://docs-staging.fused.io'

jobs:
    algolia-docs-indexing:
        # Need to uncomment this out once its tested properly 
        # if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest

        steps:
        - name: Algolia crawler creation and crawl
         uses: algolia/algoliasearch-crawler-github-actions@v1.1.13
         id: algolia_crawler
         with:
            crawler-user-id: ${{ secrets.ALGOLIA_CRAWLER_USER_ID }}
            crawler-api-key: ${{ secrets.ALGOLIA_CRAWLER_API_KEY }}
            algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
            algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
            crawler-name: "Github Actions Algolia Crawler for PR ${{github.event.pull_request.number}}"
            site-url: 'https://docs.fused.io'

    delete-s3-prefix:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest

        steps:
        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::926411091187:role/github_website_role
            role-session-name: GithubFusedLabsFusedPyReleaseDocs
            aws-region: us-west-2

        - name: Delete PR prefix
          run: |
            aws s3 rm ${{env.BUCKET_NAME}}/pr/${{github.event.pull_request.number}} --recursive
