name: Delete PR prefix on merge
run-name: Delete PR prefix on merge

on:
    pull_request:
        types: [closed]

env:
    BUCKET_NAME: 's3://docs-staging.fused.io'

jobs:
    delete-s3-prefix:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest

        steps:
        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::926411091187:role/github_website_role
            role-session-name: GithubFusedLabsFusedPyReleaseDocs
            aws-region: us-west-2

        - name: Delete PR prefix
          run: |
            aws s3 rm ${{env.BUCKET_NAME}}/pr/${{github.event.pull_request.number}} --recursive
